Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -1,9 +1,7 @@
 name: Build and Publish to Registry
 
 on:
-  push:
-    branches:
-      - canary
+  push
 
 env:
   PROJECT_ID: ${{ secrets.GKE_PROJECT }}
@@ -18,19 +16,33 @@ jobs:
     environment: dev
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    # Setup gcloud CLI
-    - name: Setup gcloud CLI
-      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
-      with:
-        service_account_key: ${{ secrets.GKE_SA_KEY }}
-        project_id: ${{ secrets.GKE_PROJECT }}
-      # Add Slack notification for success and failure
-      run: |
-        gcloud config list
-        if [ $? -eq 0 ]; then
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Setup gcloud CLI step completed successfully"}' $SLACK_WEBHOOK_URL
-        else
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Setup gcloud CLI step failed"}' $SLACK_WEBHOOK_URL
+      # Setup gcloud CLI
+      - name: Setup gcloud CLI
+        id: setup_gcloud
+        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
+        with:
+          service_account_key: ${{ secrets.GKE_SA_KEY }}
+          project_id: ${{ secrets.GKE_PROJECT }}
+        # Add Slack notification for success and failure
+        run: |
+          gcloud config list
+          if [ $? -eq 0 ]; then
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"Setup gcloud CLI step completed successfully"}' $SLACK_WEBHOOK_URL
+          else
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"Setup gcloud CLI step failed"}' $SLACK_WEBHOOK_URL
+          fi
+
+      # Configure Docker to use the gcloud command-line tool as a credential
+      - name: Configure Docker
+        run: |-
+          gcloud --quiet auth configure-docker
+        # Add Slack notification for success and failure
+        run: |
+          if [ $? -eq 0 ]; then
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"Configured Docker successfully"}' $SLACK_WEBHOOK_URL
+          else
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"Configured Docker failed"}' $SLACK_WEBHOOK_URL
+          fi
