Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -15,39 +15,22 @@ jobs:
     environment: dev
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+    - name: Checkout
+      uses: actions/checkout@v3
 
-      # Setup gcloud CLI
-      - name: Setup gcloud CLI
-        id: setup_gcloud
-        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
-        with:
-          service_account_key: ${{ secrets.GKE_SA_KEY }}
-          project_id: ${{ secrets.GKE_PROJECT }}
-
-      # Notify Slack on setup success
-      - name: Notify Slack on setup success
-        if: ${{ success() }}
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          payload: |
-            {
-              "text": "Step 1 - Setup gcloud CLI succeeded."
-            }
-
-      # Notify Slack on setup failure
-      - name: Notify Slack on setup failure
-        if: ${{ failure() }}
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          payload: |
-            {
-              "text": "Step 1 - Setup gcloud CLI failed."
-            }
-
-
-      # Configure Docker to use the gcloud command-line tool as a credential
-      # helper for authentication
-      - run: |-
-          gcloud --quiet auth configure-docker
+    # Setup gcloud CLI
+    - name: Setup gcloud CLI
+      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
+      with:
+        service_account_key: ${{ secrets.GKE_SA_KEY }}
+        project_id: ${{ secrets.GKE_PROJECT }}
+      # Add Slack notification for success and failure
+      env:
+        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      run: |
+        gcloud config list
+        if [ $? -eq 0 ]; then
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Setup gcloud CLI step completed successfully"}' $SLACK_WEBHOOK_URL
+        else
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Setup gcloud CLI step failed"}' $SLACK_WEBHOOK_URL
+        fi
